# Site settings
title: Vincent Trivett | Full Stack Developer and Code Mentor
email: trivett@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Vincent Trivett, NYC-based swiss army knife of getting stuff done on the web.
baseurl:  # the subpath of your site, e.g. /blog/
url:  http://vincenttrivett.com
twitter_username: vincent_trivett
github_username:  trivett

# Build settings
markdown: kramdown

highlighter: rouge
gems: [
  jekyll-paginate,
  hpricot,
  kramdown
  ]
# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  posts:
    output: true
    permalink: /posts/:path/
  # poetry:
  #   output: true
  #   permalink: /poetry/:path/


