---
layout: post
title: Home is Where the Art Is
date: 2006-02-15 12:37:59.000000000 -05:00
type: post
published: true
status: publish
categories:
- Writing
tags:
- '2006'
- art
- brooklyn
- homeless museum
- L magazine
- museum
- noterdaeme
- nyc

---
<p>Published in <a title="The L Magazine" href="http://www.thelmagazine.com/newyork/home-is-where-the-art-is/Content?oid=1135684">The L Magazine, February 15, 2006.</a></p>
<p>As an artist, Filip Noterdaeme is probably better known to the security staff at the Museum of Modern Art than to its curators and patrons. Noterdaeme is the organizer behind a series of quirky protest actions against the 67 percent admission hike that followed the MoMA’s recent renovation. Eyebrows were raised at the November 2004 reopening when Noterdaeme and company paid the 20-dollar charge with pennies, laboriously hauling 12 pounds of copper to dramatize the burden the increased price places on the museum-going public. On the anniversary of the “Penniless at the Modern” shenanigans, he seems to have outdone himself. In the company of his sidekicks, Madame Butterfly and a stuffed coyote named Florence, and wearing a false beard, Noterdaeme set up his MoMA HMLSS exhibit directly in front of the MoMA for a full day. This suitcase-sized museum featured miniatures of all of the MoMA’s most famous exhibits, fur cup and helicopter included. Passersby on 53rd Street were encouraged to visit this museum for free in lieu of its more expensive indoor counterpart.</p>
<p>Noterdaeme, a native of Belgium, came to New York in the mid 80s, initially to earn a BFA at the School of Visual Arts. In 1990, he began his interrupted tenure as an MFA student at Hunter. The painting that got him expelled from Hunter for “plagiarism,” a two-canvas portrait of himself with a pipe protruding from his feminized pelvis, is displayed in his museum under the title Birth of a Museum. Since then, he has been a freelance lecturer in art history at various local colleges and worked at various museums to support himself. From the moment he arrived in New York, the phenomenon of homelessness intrigued him. “When I travel on the subway to get to the Guggenheim to work,” he says, “I see at least a few homeless panhandlers. The contrast is striking. On one hand, you have this enormously funded cultural institution, and in the same place, so much abjection, powerlessness and suffering. The American Dream and the American Nightmare exist together. The homeless exist as a reminder to me of what could happen to any of us, the grim side of the same system that can create the wealth that makes a museum like the Guggenheim or the MoMA possible.”</p>
<p>Noterdaeme uses homelessness to critique what he sees as a haughty high-art scene and a society capable of simultaneously producing homeless people and elite art galleries. The cheeky MoMA HMLSS operation is only adjunct to Noterdaeme’s magnum opus conceptual art project, the Homeless Museum , which takes up every inch of his two-bedroom walk-up in Brooklyn Heights. Though he is officially the “director” of this half-fictitious museum, Noterdaeme is also the creative mind behind all of its “acquisitions.” One might expect a “Homeless Museum” to be some sort of anthropological museum, an homage to the homeless; a theme museum not unlike the Lower East Side Tenement Museum, a Holocaust Museum, or at worst, a mere fundraising technique for a charitable organization. What one finds at HoMu is something else altogether. The entire apartment is a pastiche of a museum or gallery. Each room is given a bureaucratic role. For instance, the bathroom is labeled the “Curatorial Department,” a “place for serious business and private meetings.” All of the museum’s inhabitants, stuffed coyote included, are listed among its Board of Trustees. The walls are all painted a flat white. In his letters to other museum directors, Noterdaeme would use the proper, respectful tone of a real museum director writing to a colleague while proposing, for instance, that the HoMu squat on the roof of the Guggenheim.</p>
<p>One of the highlights of the Homeless Museum, that perfectly captures its spirit of mockery, is the $0.00 Collection. This piece arrays a group of color-coordinated found objects not unlike the sort of trash carried about and sold by homeless people. Above each group is a tiny reproduction of a classical painting of a corresponding color in a milk crate. Homelessness, for Noterdaeme, is the last frontier of the marketable, the last unsellable disgust left unappropriated by commerce. The $0.00 Collection deliberately resists commercial value through its title. Art today is consumed more than it is experienced, and that is something that the live-in, interactive museum attempts to turn around. The $0.00 collection confronts this with a set or readymades that can be reproduced by anyone, perhaps especially homeless people.</p>
<p>A normal museum is something that separates and walls off art from everyday life. Noterdaeme proudly makes the point that he lives in his museum. Most people living in New York would be shocked that anyone can find space for a “museum” to squat in their apartment. Noterdaeme insists that his museum/apartment is actually a functional, economical space. “Take for instance, the Curatorial Department,” he says. “We needed a place where we can curate! We needed a place to put our slideshow of classical masterpieces, too. We couldn’t add another wing to the apartment. That would be too expensive, it wouldn’t be economical. So we put the Curatorial Department in the bathroom. Likewise, the refrigerator serves as a membership safe, the kitchen transforms into the Café Broodthaers while we are entertaining a visitor. What is more functional than that?” Holding a museum in a normal-sized apartment involves some tricky division of labor. Noterdaeme himself occupies the role of janitor as well as director. Madame Butterfly serves as the Director of Development. The aforementioned stuffed coyote is HoMu’s official Director of Public Relations. A nearly defunct robot serves as Treasurer when he isn’t panhandling for fresh batteries.</p>
<p>Noterdaeme is currently planning a “New HoMu,” an enormous cube of orange soap that will be displayed in public in Kansas City. Visitors to this museum will be encouraged to excavate an interior of it for themselves and take any fragments of it with them as souvenir sculptures. Being outdoors, the soap museum will only exist for as long as the elements allow. “I don’t want to define how you feel when you enter my museum. I mean, this audio tour is a joke, really. Most museums offer an audio tour, a monologue that leaves no possibility for the viewer to define his own experience.”</p>
<p>When I came to visit, Filip and Madame Butterfly were on there way to Spain, taking along their MoMA HMLSS exhibit, probably as a carry-on. Filip reminded me, “I am bringing this with me to Madrid. I always have art with me. I work at museums, I go to museums, I live in a museum, and I keep myself surrounded by art. I think that true homelessness starts when we become estranged from culture...“ “That’s what this is all about, really,” Madame Butterfly interrupted. “If I knew what this was all about,” Filip replied, “that might be it.”</p>
