---
layout: post
title: Will the JOBS Act Open Floodgates of Innovation or Fraud?
date: 2012-03-19 18:59:14.000000000 -04:00
type: post
published: true
status: publish
categories:
- Writing
tags: []

excerpt: Entrepreneurs are cheering Congress to make it easier to go public, but investors
  are concerned about the loss of accountability and protections.
---
<p>Tomorrow the Senate will vote on one of those rare bills that that has vast bipartisan support. It passed through the House with 390 yeas to only 23 nays, and <a href="http://www.whitehouse.gov/sites/default/files/omb/legislative/sap/112/saphr3606h_20120306.pdf">Barack Obama supports it, too</a>. How could this possibly be controversial?</p>
<p>The bill is called the Jumpstart Our Business Startups Act, and includes several measures of <a href="http://www.whitehouse.gov/economy/business/startup-america">the President’s Startup America</a> agenda, which aims to boost hiring by unleashing the entrepreneurial animal spirits of small businesses.</p>
<p>Investors are protesting against some of the bill's provisions that roll back securities regulations designed to protect investors from fraud.</p>
<p>Part of the <a href="http://docs.house.gov/billsthisweek/20120305/CPRT-112-HPRT-RU00-HR3606Floor_xml.pdf">House version of the bill</a> aims to establish a regulatory "on ramp” to make it easier for young companies to go public. The bill’s supporters have a point. The president and much of Congress are right to hope that high-tech entrepreneurs can help get Americans back to work. According to ADP, a payroll company, not only does a plurality of Americans work for small companies, half of all job gains last month came from companies with <a href="http://www.minyanville.com/business-news/the-economy/articles/investors-markets-jobs-act-sarbox-sarbanes/3/19/2012/id/39966#">less than 50 employees</a>. Small businesses like startups usually hire at the fastest rate during their early growth spurts. According to Tennessee Republican Stephen Fincher, the representative that introduced the bill, 92% of hiring happens after a company goes public. The past decade had far fewer IPOs than the 1990s, and Hong Kong now hosts the lion’s share of world IPOs, often for non-Chinese companies.</p>
<p>Ernst &amp; Young says that on average,<a href="http://www.ey.com/US/en/Newsroom/News-releases/News_True-Costs-of-IPOs-Survey-Finds-Investing-in-Management-Team-is-Central-Element-to-Companies-Going-Public"> companies burn through $2.5 million annually</a> for the pleasure of having access to capital markets. Even if regulatory compliance is not the biggest cost of going public, lowering costs can possibly make it easier for small companies to go public and still have more money left over to expand and hire new workers.</p>
<p>Last week, about 700 CEOs and presidents of startup businesses signed a letter sent on behalf of the National Venture Capital Association urging the Senate to pass the Act to change securities regulations to make it easier for startups to go public.</p>
<p>“During the past decade, emerging growth companies have faced numerous new challenges when considering an IPO,” the letter says. “The regulatory on-ramp provisions thoughtfully address many of these issues and, for the first time in years, will provide much needed support for small companies with big potential.”</p>
<p>The “on-ramp” provision is of particular concern to investors. It lowers the regulatory hurdles that have to be overcome by a company that wants its stock to become accessible to investors on exchanges such as the <strong>New York Stock Exchange</strong> and <strong>Nasdaq</strong>. Giving startups a chance to go public and get established before hitting them with regulations is broadly supported, but some of these regulations are investor protections that date back just 10 years to the Sarbanes-Oxley Act that passed in response to the dot-com bust and accounting scandals of Enron and Worldcom.</p>
<p>Institutional investors are protesting the on-ramp measures because the rules that this bill does away with are important investor safeguards. Companies in the new class of “emerging growth” will be able to avoid certain costly regulations for five years, or until they get $1 billion in yearly revenue or a market capitalization of $700 million. For example, companies in the regulatory on-ramp will be allowed to raise tens of millions of dollars on public markets without making regular reports to the Securities and Exchange Commission or giving investors audited financial statements. Previously, companies had to show three years of audited financial statements to go public. This bill cuts it down to two years. Without an independent audit, investors, especially unsophisticated ones, are vulnerable to fraud.</p>
<p>This takes away the protection against fraudulent companies that investors currently enjoy. Without audited statements, a company could float on the market without any real proof of what it is doing. John Coffee, a law professor at Columbia University said, “you could call this bill the Boiler Room Legislation Act of 2011,” referring to the fraudulent stock schemes that the film <em>Boiler Room</em> is based on. <a href="http://banking.senate.gov/public/index.cfm?FuseAction=Files.View&amp;FileStore_id=d580503c-a7f3-4db5-b9f5-968d03af374f">In his testimony before Congress</a>, Coffee suggested that the costs of going public could be pared without throwing the baby out with the bathwater. He said, that the bill “in its present form, seems likely to invite a significant amount of fraud that could, over the longer run, stigmatize those attempting to market smaller offerings. Still, with some adjustments that would not raise the costs of such an offering procedure, I believe that the potential for fraud and 'boiler room' marketing could be substantially curtailed.”</p>
<p>Other controversial measures will exempt emerging growth companies from Sarbanes-Oxley’s “Say-on-Pay” regulation as well as Dodd-Frank Act rules on <a href="http://www.minyanville.com/business-news/the-economy/articles/investors-markets-jobs-act-sarbox-sarbanes/3/19/2012/id/39966#">executive compensation</a> for a number of years. It also allows for crowdfunding of startups open to small investors that are not classified as qualified institutional buyers.</p>
<p>Another part of the bill would actually make it easier <em>not </em>to go public. Currently, a company that crosses a threshold of 500 investors of record is required to file with the Securities and Exchange Commission. The JOBS Act will make that 2,000. If this was law a few months earlier, Facebook would not be going public soon.</p>
<p>As the bill’s acronym suggests, the purpose of this is ostensibly to increase hiring, but not all are convinced that deregulation of capital markets will necessarily result in shorter lines at the unemployment office.</p>
<p>The Corporate Council is one organization that is skeptical of this bill for this reason.</p>
<p>“Beyond the obvious question of whether, as the name implies,<strong> </strong>these securities law tweaks will actually have any impact at all on the employment market, some have raised concern with the investor protections that might be compromised by some of these legislative initiatives,” <a href="http://www.thecorporatecounsel.net/Blog/2012/03/house-passes-jobs-act-seeking-to-fast-track-capital-formation-reforms.html">Corporation Council representative Dave Lynn said in a statement</a>.</p>
<p>Former SEC Chief Accountant Lynn Turner <a href="http://banking.senate.gov/public/index.cfm?FuseAction=Files.View&amp;FileStore_id=5aaabb66-36eb-4b1e-8195-3cbeda832814">warned Congress</a> of the harm that could come to financial markets without investor safeguards in a lengthy testimony last year.</p>
<p>“More jobs and a larger number of qualified IPOs is something we all strive for.  But IPOs have to be successful for not only those selling stock, but also for those buying shares,” he said. "This legislation is currently unbalanced and likely to result in more unsuccessful investments for investors.  In the long run, history has judged clearly that such incidents serve to reduce IPO’s,cost jobs, and cost investors money sorely needed for retirement and education.”</p>
<p>For <a href="http://www.minyanville.com/business-news/the-economy/articles/investors-markets-jobs-act-sarbox-sarbanes/3/19/2012/id/39966#ixzz1wIomyUhb">Minyanville</a>.</p>
